package com.erjiao.cxf.frontend.jaxwsfrontend.contractfirst;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.5.9
 * 2016-05-12T21:34:50.160+08:00
 * Generated source version: 2.5.9
 * 
 */
@WebServiceClient(name = "OrderProcessService", 
                  wsdlLocation = "src/com/erjiao/cxf/frontend/jaxwsfrontend/contractfirst/demo.wsdl",
                  targetNamespace = "http://order.demo/") 
public class OrderProcessService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://order.demo/", "OrderProcessService");
    public final static QName OrderProcessPort = new QName("http://order.demo/", "OrderProcessPort");
    static {
        URL url = OrderProcessService.class.getResource("src/com/erjiao/cxf/frontend/jaxwsfrontend/contractfirst/demo.wsdl");
        if (url == null) {
            java.util.logging.Logger.getLogger(OrderProcessService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "src/com/erjiao/cxf/frontend/jaxwsfrontend/contractfirst/demo.wsdl");
        }       
        WSDL_LOCATION = url;
    }

    public OrderProcessService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public OrderProcessService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public OrderProcessService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public OrderProcessService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public OrderProcessService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public OrderProcessService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns OrderProcess
     */
    @WebEndpoint(name = "OrderProcessPort")
    public OrderProcess getOrderProcessPort() {
        return super.getPort(OrderProcessPort, OrderProcess.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns OrderProcess
     */
    @WebEndpoint(name = "OrderProcessPort")
    public OrderProcess getOrderProcessPort(WebServiceFeature... features) {
        return super.getPort(OrderProcessPort, OrderProcess.class, features);
    }

}
