package com.erjiao.cxf.frontend.jaxwsfrontend.contractfirst;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.5.9
 * 2016-05-12T21:34:50.146+08:00
 * Generated source version: 2.5.9
 * 
 */
@WebService(targetNamespace = "http://order.demo/", name = "OrderProcess")
@XmlSeeAlso({ObjectFactory.class})
public interface OrderProcess {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "processOrder", targetNamespace = "http://order.demo/", className = "com.erjiao.cxf.frontend.jaxwsfrontend.contractfirst.ProcessOrder")
    @WebMethod
    @ResponseWrapper(localName = "processOrderResponse", targetNamespace = "http://order.demo/", className = "com.erjiao.cxf.frontend.jaxwsfrontend.contractfirst.ProcessOrderResponse")
    public java.lang.String processOrder(
        @WebParam(name = "arg0", targetNamespace = "")
        com.erjiao.cxf.frontend.jaxwsfrontend.contractfirst.Order arg0
    );
}
